#!/usr/bin/env node

var dbf = require("./dbf");

dbf.readStream("/dev/stdin")
    .on("header", function(header) { console.log("header", header); })
    .on("record", function(record) { console.log("record", record); })
    .on("end", function() { console.log("end"); });
