#!/usr/bin/env node

var shp = require("./shp");

shp.readStream("/dev/stdin")
    .on("header", function(header) { console.log("header", header); })
    .on("record", function(record) { console.log("record", record.shapeType); })
    .on("end", function() { console.log("end"); });
